#!/bin/bash
#Distributed under the terms of the GNU GPL version 2.


die()
{
        echo $1; return $2
}

show_lisence()
{
	echo -e "todo ..." | fmt -w 104
	return 0
}

show_donation()
{
	echo -e "todo ..." | fmt -w 104
	return 0
}

